### ISSUE TITLE
Error: We're sorry, but Hacker News Summarizer was unable to produce a summary for this article

### ISSUE THREAD

**Issue by joihn** [bishalpaudel/hnsummarizer#1]
HI, thanks, for this awesome tool ! However, As of 24 april, all article on Hackernews gives me:
`
Error: We're sorry, but Hacker News Summarizer was unable to produce a summary for this article
`

**Comment by bishalpaudel** [comment]
Hi @joihn 
Thanks for opening this issue. There was an issue with the backend api, which is now resolved.
